language: objective-c
matrix:
  include:
    - env: OSX=10.11 HOMEBREW_RUBY=2.0.0
      os: osx
      osx_image: xcode7.2
      rvm: system
    - env: OSX=10.10 HOMEBREW_RUBY=2.0.0
      os: osx
      osx_image: xcode7.1
      rvm: system
script:
  - brew uninstall --force brew-cask
  - brew update
  - brew tap caskroom/cask
  - brew tap cosmo0920/cask-coreclr
  - sudo brew cask install coreclr
  - sudo brew cask uninstall coreclr